apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: kube-system
  labels:
    grafana_datasource: "1"
    app: prometheus-operator-grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://39.106.124.113:31001
      access: direct
