apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: ns-monitor
  labels:
    name: my-test-pod
spec:
  nodeName: node22
  containers:
  - name: test-pod
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","sleep 3600"]
